# Generated by Django 6.0.1 on 2026-02-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('PRIMARY', 'Primary Residence'), ('SECOND', 'Second Home'), ('RENTAL', 'Rental Property'), ('TIMESHARE', 'Time Share'), ('HELOC', 'HELOC')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.household')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('CHILD', 'Child'), ('OTHER', 'Other')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Fortuneriseapp.household')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('TERM', 'Term'), ('PERM', 'Permanent'), ('WL', 'Whole Life')], max_length=10)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.household')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('RENTAL', 'Rental'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(max_length=20)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('AUTO', 'Auto Loan'), ('BOAT', 'Boat Loan'), ('CREDIT_CARD', 'Credit Card'), ('MEDICAL', 'Medical'), ('PERSONAL', 'Personal Loan'), ('STUDENT', 'Student Loan'), ('OTHER', 'Other')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.household')),
                ('owner', models.ManyToManyField(to='Fortuneriseapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='ChildExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('EDUCATION', 'Education'), ('CHILDCARE', 'Child Care')], max_length=20)),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FIXED', 'Fixed Asset'), ('VARIABLE', 'Variable Asset'), ('INDEXED', 'Indexed Asset')], max_length=10)),
                ('asset_type', models.CharField(choices=[('BOND', 'Bond'), ('CD', 'CD'), ('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY_MARKET', 'Money Market'), ('BITCOIN', 'Bitcoin'), ('MUTUAL_FUND', 'Mutual Fund'), ('STOCK', 'Stock'), ('OPTION', 'Option'), ('HSA', 'HSA'), ('ANNUITY', 'Annuity'), ('IRA', 'IRA'), ('401K', '401K'), ('403B', '403B'), ('PENSION', 'Pension'), ('SOLO_401K', 'Solo 401K'), ('SEP_IRA', 'SEP IRA'), ('SIMPLE_IRA', 'SIMPLE IRA'), ('ROTH_IRA', 'ROTH IRA'), ('PLAN_529', '529'), ('IUL', 'IUL CV'), ('FIA', 'FIA')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fortuneriseapp.household')),
                ('owner', models.ManyToManyField(to='Fortuneriseapp.person')),
            ],
        ),
    ]
